INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Aeropostale', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Ropa Aeropostale', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Carter''s', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Carters', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Carter', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Ropa Carters', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Ropa Bebé', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Ropa Bebé Carters', 0, 0, 0)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Bath & body ', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Splash Bath and Body', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Splash Bath & body', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Splash', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Splash Victoria Secret', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Colonia', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Brillos Victoria Secret', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Brillos', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Brillos Aeropostale', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Mantequillas', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Perfumes', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Sudaderas', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('camisetas polo', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Polo', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Camisetas', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Busos', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Chompas', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Hoodie', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Vitaminas', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Vs fantasies', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Jeans', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Shorts', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Ropa Baby', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Pink', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Sally hansen', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Airbrush Leg', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Air Brush Leg', 0, 0, 1)
INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('Maquillaje piernas', 0, 0, 1)



--INSERT INTO [dbo].[Busquedas] ([Texto], [ContadorBusquedas], [Eliminado], [Aprobado]) VALUES('', 0, 0, 0)