INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(0,'Sin Categoría','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(0,'Tecnologia','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(2,'Audio y Video','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(2,'Informatica','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(2,'Celulares y Telefonos','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(2,'Electrodomesticos','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(2,'Video Juegos','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(2,'Cocina','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(2,'Ferreteria','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(0,'Hogar','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(10,'Interiores','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(10,'Exteriores','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(10,'Alcobas','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(10,'Baños','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(10,'Cocina','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(0,'Salud Y Belleza','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(16,'Cuidado del cuerpo','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(16,'Cuidado de la piel','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(16,'Cuidado Cabello',' ','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(16,'Perfumes y Fragancias','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(16,'Maquillaje','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(0,'Deportes y Fitness','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(22,'Ciclismo','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(22,'Accesoriospara el Hogar','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(22,'Equipo para gimnasio','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(22,'Elásticos','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(22,'Guantes y Cinturones','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(22,'Mancuernas','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(22,'Otros','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(0,'Alimentación','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(30,'Activadores, Energéticos e Hidratantes','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(30,'Proteinas','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(32,'Ganadores de peso','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(32,'Perdida de peso','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(32,'Mantenimiento','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(30,'Glutaminas','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(30,'Creatinas','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(30,'Aminoacidos','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(30,'Vitaminas y Minerales','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(30,'Naturistas','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(30,'Otros','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(0,'Juguetes','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(42,'Peluches','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(42,'Figuras Acción','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(42,'Radio control','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(45,'Helicopteros','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(45,'Aviones ','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(45,'Automoviles','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(42,'Educativos y didacticos','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(49,'Bebe','','bebe,baby')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(49,'Deportes','','deportes,sport')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(49,'Cocina','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(42,'Juegos de mesa','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(0,'Bebes','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(54,'Alimentacion','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(54,'Habitacion','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(54,'Juguetes','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(54,'Higiene y Salud','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(54,'Seguridad','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(54,'Sillas y coches','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(0,'Ropa y Accesorios','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(61,'Hombre','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(61,'Mujer','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(61,'Niños','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(61,'Niñas','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(61,'Bebito','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(61,'Bebita','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(0,'Muebles','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(68,'Dormitorio','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(68,'Sala y comedor','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(68,'Oficina y estudio',' ','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(0,'Vehiculos','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(72,'Motos','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(73,'Accesorios','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(73,'Herramientas','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(73,'Indumentaria','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(72,'Carros','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(77,'Accesorios','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(77,'Audio y Video','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(77,'GPS','','')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(77,'Herramientas','','')


/*Subcategorias Perfumes y Fragancias*/
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(20,'Hombre','perfumes y fragancias para hombre, con y sin feromonas, para uso diario y ocasiones especiales. Envios a toda colombia comprando en línea por diferentes medios de pago','perfumes de hombre, fragancias de hombre, perfumes para hombre, perfumes con feromonas')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(20,'Mujer','Compra en línea con envío a toda Colombia Perfumes y fragancias para mujer con y sin feromonas, para todo momento y lugar, diferentes marcas','perfumes de mujer, fragancias de mujer, perfumes para mujer, splash, splash con feromonas, perfumes con feromonas')

/*Subcategorías Ropa de Hombre*/

INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(62,'Busos','Busos para hombre importados de los estados unidos, compre online y reciba en la puerta de su casa, encuentre para diferentes climas, con o sin capucha','buzos, busos hombre, busos para hombre, buzos estampados, buzos deportivos, hoodies')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(62,'Camisas','Compra en línea camisas con envío a toda colombia y reciba en su puerta en poco tiempo camisas importadas para mujer, de las mejores marcas','camisas hombre, camisas para hombre, camisetas, camisas estampadas, camisas bordadas')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(62,'Camisetas','Camisetas para hombre importadas, en diferentes estilos, con estampados o bordados, prendas frescas y cómodas para los tiempos modernos','camiseta de hombre, camisetas colombia, camisetas estampadas, moda masculina')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(62,'Chaquetas','Chaquetas para hombre en diferentes estilos y para diferentes ocasiones, compre en línea y reciba en la puerta de su casa','chaqueta para hombre, chaquetas hombre, chaqueta de cuero')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(62,'Gafas','Gafas para hombre importadas de los estados unidos, solo lo último en moda para dama, ya sea un día de solo o un día nublado, compre en línea y reciba en la puerta de su casa','gafas para hombre, las gafas, gafas de sol, gafas carrera, cagas de moda, gafas deportivas')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(62,'Jeans','Jeans para hombre importados y nacionales de las mejores marcas, destacan la figura femenina con toda su belleza, compre en línea será entregado en la puerta de su casa','jeans hombre, blue jeans, jeans usa, jeans importados, jeans medellin, jeans de moda')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(62,'Ropa Deportiva','Compre en línea y reciba el paquete en la puerta de su casa, ropa deportiva de las mejores marcas para el hombre deportista de hoy.','ropa deportiva hombre, ropa deportiva colombia, ropa deportiva medellin, ropa deportiva de marca')

/*SubCategorías Ropa de Mujer*/
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(63,'Blusas','Blusas para mujer de diferentes marcas y estilos, compre en linea y reciba en la puerta de su casa','moda blusas, moda, blusas de moda ')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(63,'Busos','Busos para mujer importados de los estados unidos, compre online y reciba en la puerta de su casa, encuentre para diferentes climas, con o sin capucha','buzos, busos mujer, busos para mujer, buzos estampados, buzos deportivos, hoodies')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(63,'Camisas','Compra en línea camisas con envío a toda colombia y reciba en su puerta en poco tiempo camisas importadas para mujer, de las mejores marcas','camisas mujer, camisas para mujer, camisetas, camisas estampadas, camisas bordadas')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(63,'Camisetas','Camisetas para mujer importadas, en diferentes estilos, con estampados o bordados, prendas frescas y cómodas para los tiempos modernos','camiseta de mujer, camisetas colombia, camisetas estampadas')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(63,'Chaquetas','Chaquetas para mujer, para diferentes ocasiones en estilos variados y orientadas a diferentes situaciones climáticas, compre en línea y reciba en la puerta de su casa','chaqueta para mujer, chaquetas mujer, chaqueta de cuero')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(63,'Gafas','Gafas para mujer en diferentes estilos a la moda, proteja sus ojos con los mejor, solo importadas de las mejores marcas directo hasta su puerta a nivel nacional','gafas para mujer, las gafas, gafas de sol, gafas carrera, cagas de moda, gafas deportivas')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(63,'Jeans','Jean para mujer en diferentes estilos, para todo momento, productos importados y nacionales con envíos a todo colombia hasta su puerta','jeans mujer, blue jeans, jeans usa, jeans importados, jeans medellin, jeans de moda')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(63,'Pijamas','Pijamas para mujer en diferentes estilos y tamaños para todo gusto, momento, clima','pijamas mujer, pijamas sexys, pijamas medellin, pijamas bogota')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(63,'Ropa Deportiva','Ropa deportiva para mujer, prendas que resaltan la figura femenina y entregan la comodidad que facilita el entrenamiento, compre en línea y reciba en al puerta de su cas a nivel nacional','ropa deportiva mujer, ropa deportiva colombia, ropa deportiva medellin, ropa deportiva de marca')
INSERT INTO [Categoria] ([IdCategoriaPadre],[Nombre],[Descripcion],[PalabrasClaves])VALUES(63,'Ropa Interior','Ropa interior de las mejores marcas americanas importadas para su disfrute, compre su prenda en línea y reciba en la puerta de su casa','Ropa Interior Mujer, catalogo ropa femenina, catalogos de ropa online, lenceria')