-- =============================================
-- Script Template
-- =============================================
INSERT INTO Color(Codigo,Nombre) VALUES('FFFFFF', 'Sin Color')
INSERT INTO Color(Codigo,Nombre) VALUES('FFFF00', 'Amarillo')
INSERT INTO Color(Codigo,Nombre) VALUES('FFD700', 'Amarillo Dorado')
INSERT INTO Color(Codigo,Nombre) VALUES('DAA520', 'Amarillo Dorado Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('ADFF2F', 'Amarillo Verde')
INSERT INTO Color(Codigo,Nombre) VALUES('9ACD32', 'Amarillo Verde Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('00FFFF', 'Aqua')
INSERT INTO Color(Codigo,Nombre) VALUES('7FFFD4', 'Aqua Marina')
INSERT INTO Color(Codigo,Nombre) VALUES('66CDAA', 'Aqua Marina Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('0000FF', 'Azul')
INSERT INTO Color(Codigo,Nombre) VALUES('4682B4', 'Azul Acero')
INSERT INTO Color(Codigo,Nombre) VALUES('B0C4DE', 'Azul Acero Claro')
INSERT INTO Color(Codigo,Nombre) VALUES('6495ED', 'Azul Aciano')
INSERT INTO Color(Codigo,Nombre) VALUES('87CEEB', 'Azul Cielo')
INSERT INTO Color(Codigo,Nombre) VALUES('00BFFF', 'Azul Cielo Profundo')
INSERT INTO Color(Codigo,Nombre) VALUES('E0FFFF', 'Azul Cyan')
INSERT INTO Color(Codigo,Nombre) VALUES('00008B', 'Azul Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('B0E0E6', 'Azul Polvo')
INSERT INTO Color(Codigo,Nombre) VALUES('4169E1', 'Azul Rey')
INSERT INTO Color(Codigo,Nombre) VALUES('F5F5DC', 'Beige')
INSERT INTO Color(Codigo,Nombre) VALUES('FFFFFF', 'Blanco')
INSERT INTO Color(Codigo,Nombre) VALUES('A52A2A', 'Café')
INSERT INTO Color(Codigo,Nombre) VALUES('800000', 'Café (Marrón)')
INSERT INTO Color(Codigo,Nombre) VALUES('A0522D', 'Café Sienna')
INSERT INTO Color(Codigo,Nombre) VALUES('D2691E', 'Chocolate')
INSERT INTO Color(Codigo,Nombre) VALUES('FF7F50', 'Coral')
INSERT INTO Color(Codigo,Nombre) VALUES('A9A9A9', 'Gris')
INSERT INTO Color(Codigo,Nombre) VALUES('D3D3D3', 'Gris Claro')
INSERT INTO Color(Codigo,Nombre) VALUES('778899', 'Gris Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('C0C0C0', 'Gris Plateado')
INSERT INTO Color(Codigo,Nombre) VALUES('696969', 'Gris Tenue')
INSERT INTO Color(Codigo,Nombre) VALUES('F0E68C', 'Kaqui')
INSERT INTO Color(Codigo,Nombre) VALUES('BDB76B', 'Kaqui Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('FFDAB9', 'Melocotón')
INSERT INTO Color(Codigo,Nombre) VALUES('FFA500', 'Naranja')
INSERT INTO Color(Codigo,Nombre) VALUES('FF8C00', 'Naranja Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('000000', 'Negro')
INSERT INTO Color(Codigo,Nombre) VALUES('808000', 'Oliva')
INSERT INTO Color(Codigo,Nombre) VALUES('556B2F', 'Oliva Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('B8860B', 'Oro Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('800080', 'Púrpura')
INSERT INTO Color(Codigo,Nombre) VALUES('BA55D3', 'Púrpura (Orquidea)')
INSERT INTO Color(Codigo,Nombre) VALUES('DDA0DD', 'Purpura Claro')
INSERT INTO Color(Codigo,Nombre) VALUES('4B0082', 'Púrpura Indigo')
INSERT INTO Color(Codigo,Nombre) VALUES('9370DB', 'Púrpura Medio')
INSERT INTO Color(Codigo,Nombre) VALUES('C71585', 'Púrpura Rojo')
INSERT INTO Color(Codigo,Nombre) VALUES('EE82EE', 'Púrpura Violeta')
INSERT INTO Color(Codigo,Nombre) VALUES('FF0000', 'Rojo')
INSERT INTO Color(Codigo,Nombre) VALUES('FF4500', 'Rojo Naranja')
INSERT INTO Color(Codigo,Nombre) VALUES('FFC0CB', 'Rosa')
INSERT INTO Color(Codigo,Nombre) VALUES('FF00FF', 'Rosa Intenso (Fucsia)')
INSERT INTO Color(Codigo,Nombre) VALUES('FF69B4', 'Rosa Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('FF1493', 'Rosa Profundo')
INSERT INTO Color(Codigo,Nombre) VALUES('FA8072', 'Salmon')
INSERT INTO Color(Codigo,Nombre) VALUES('E9967A', 'Salmon Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('FFFFFF', 'Transparente')
INSERT INTO Color(Codigo,Nombre) VALUES('40E0D0', 'Turquesa')
INSERT INTO Color(Codigo,Nombre) VALUES('00CED1', 'Turquesa Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('008000', 'Verde')
INSERT INTO Color(Codigo,Nombre) VALUES('90EE90', 'Verde Claro')
INSERT INTO Color(Codigo,Nombre) VALUES('00FF00', 'Verde Lima')
INSERT INTO Color(Codigo,Nombre) VALUES('32CD32', 'Verde Lima Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('2E8B57', 'Verde Oceano')
INSERT INTO Color(Codigo,Nombre) VALUES('20B2AA', 'Verde Oceano Claro')
INSERT INTO Color(Codigo,Nombre) VALUES('3CB371', 'Verde Oceano Medio')
INSERT INTO Color(Codigo,Nombre) VALUES('8FBC8B', 'Verde Oceano Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('006400', 'Verde Oscuro')
INSERT INTO Color(Codigo,Nombre) VALUES('00FF7F', 'Verde Primavera')
