CREATE TABLE [dbo].[DetalleAlbaran]
(
	[IdDetalleAlbaran] [int] IDENTITY(1,1) NOT NULL,
	[IdAlbaran] [int] NOT NULL,
	[IdCliente] [int] NOT NULL,
	[NombreMarca] [nvarchar](20) NOT NULL,
	[Titulo] [nvarchar](50) NOT NULL,
	[NombreUnidadVolumen] [nvarchar](40) NOT NULL,
	[VlrVolumenLargo] [float] NOT NULL,
	[VlrVolumenAncho] [float] NOT NULL,
	[VlrVolumenProfundidad] [float] NOT NULL,
	[VlrContenidoVolumetrico] [float] NOT NULL,
	[NombreUnidadMasa] [nvarchar](20) NOT NULL,
	[VlrUnidadMasa] [float] NOT NULL,
	[NombreUnidadLongitud] [nvarchar](20) NOT NULL,
	[VlrUnidadLongitud] [float] NOT NULL,
	[NombreTalla] [nvarchar](20) NOT NULL,
	[NombreColor] [nvarchar](25) NOT NULL,
	[NombreSabor] [nvarchar](20) NOT NULL,
	[PrecioVenta] [float] NOT NULL,
	[Cantidad] [int] NOT NULL,
	[CostoDelProducto] [float] NOT NULL,
	[SubTotalVenta] [float] NOT NULL,
	[SubtotalCosto] [float] NOT NULL,
	[NombreCategoria] [nvarchar](60) NOT NULL,
	[CaminoSubCategorias] [nvarchar](250) NOT NULL,
	[IdPresentacionArticulo] [int] NOT NULL,
	[NombreUnidadPresentacion] [nvarchar](40) NOT NULL,
	[VlrUnidadPresentacion] [float] NOT NULL, 
    [AbonoDesdeFacturacion] BIT NOT NULL, 
    CONSTRAINT [PK_DetalleAlbaran] PRIMARY KEY ([IdDetalleAlbaran])
)
