CREATE TABLE [dbo].[DetalleVentaWeb]
(
	IdDetalleVentaWeb int IDENTITY(1,1) NOT NULL, 
	IdVentaWeb int NOT NULL,
	IdCliente int NOT NULL,
	NombreMarca nvarchar(20) NOT NULL,
	Titulo nvarchar(50) NOT NULL,
	--CodigoEAN nvarchar(18) NOT NULL,
	NombreUnidadVolumen nvarchar(40) NOT NULL,
	VlrVolumenLargo FLOAT NOT NULL,
	VlrVolumenAncho FLOAT NOT NULL,
	VlrVolumenProfundidad FLOAT NOT NULL,
	VlrContenidoVolumetrico FLOAT NOT NULL,
	NombreUnidadMasa nvarchar(20) NOT NULL,
	VlrUnidadMasa FLOAT NOT NULL,
	NombreUnidadLongitud nvarchar(20) NOT NULL,
	VlrUnidadLongitud FLOAT NOT NULL,
	NombreTalla nvarchar(20) NOT NULL,
	NombreColor nvarchar(25) NOT NULL,
	NombreSabor nvarchar(20) NOT NULL,
	PrecioVenta float NOT NULL,
	Cantidad int NOT NULL,
	CostoDelProducto float NOT NULL,
	SubTotalVenta float NOT NULL,
	SubtotalCosto float NOT NULL,
	NombreCategoria nvarchar(60) NOT NULL,
	CaminoSubCategorias nvarchar(250) NOT NULL,
	IdPresentacionArticulo int NOT NULL,
	NombreUnidadPresentacion nvarchar(40) NOT NULL,
	VlrUnidadPresentacion FLOAT  NOT NULL
)