CREATE TABLE PresentacionArticulo
(
	IdPresentacionArticulo int IDENTITY(1,1) NOT NULL, 
	IdArticulo int NOT NULL,
	CodigoEAN nvarchar(30) NOT NULL,
	Nombre nvarchar(100) NOT NULL,
	DescripcionBreve nvarchar(250) NOT NULL,
	IdColor int NOT NULL,
	IdTalla int NOT NULL,
	Imagen1 bit NOT NULL,
	Imagen2 bit NOT NULL,
	Imagen3 bit NOT NULL,
	Imagen4 bit NOT NULL,
	Imagen5 bit NOT NULL,
	Imagen6 bit NOT NULL,
	Fecha date NOT NULL,
	VlrUnidadMasa float NOT NULL,
	VlrUnidadVolumenLargo FLOAT NOT NULL,
	VlrUnidadVolumenAncho FLOAT NOT NULL,
	VlrUnidadVolumenProfundidad FLOAT NOT NULL,
	VlrContenidoVolumetrico FLOAT NOT NULL,
	VlrUnidadLongitud FLOAT NOT NULL,
	IdUnidadMasa int NOT NULL,
	IdUnidadVolumen int NOT NULL,
	IdUnidadLongitud int NOT NULL,
	EnLinea bit NOT NULL,
	Activo bit NOT NULL,
	Precio float NOT NULL,
	Existencias int NOT NULL,
	IdSabor int NOT NULL,
	CostoArticulo float NOT NULL,
	PreOrden bit NOT NULL, 
    [IdUnidadPresentacion] INT NOT NULL, 
    [VlrUnidadPresentacion] FLOAT NOT NULL, 
    [Actualizar] BIT NOT NULL,
	[FechaProximoVencimiento] DATE,
	[UsarFechaProximoVencimiento] bit NOT NULL,
	[UsarDescuento] bit NOT NULL,
	[UsarPorcentajeDescuento] bit NOT NULL,
	[ValorPorcentajeDescuento] float NOT NULL,
	[UsarValorFijoDescuento] bit NOT NULL,
	[ValorFijoDescuento] float NOT NULL,
	[FechaInicioDescuento] date NOT NULL,
	[FechaFinalDescuento] date NOT NULL
)
	
